# Generated by Django 5.1.2 on 2024-10-17 14:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_cooperative_memebre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memebre',
            new_name='Membre',
        ),
    ]
